### PR TITLE
test: fix flaky test in literal expression

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

This attempts to fix the flaky test which has been causing build failures for a while, e.g. https://github.com/bpmn-io/dmn-js/actions/runs/11365121269/job/31612772137?pr=909

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
I included https://github.com/bpmn-io/dmn-js/pull/910/commits/d452c8a9b14155a7b6d8474a7bc0248cca8b0478 in this PR so that CI can be green,

**Comment by barmac** [comment]
There's another flaky test in the project :D
https://github.com/bpmn-io/dmn-js/actions/runs/11366421982/job/31616761294?pr=910#step:5:1127

**Comment by barmac** [comment]
I've reworked the test to use the API as there's no need to fiddle with DOM elements.

**Review by nikku — APPROVED** [review]
Great changes :1st_place_medal:

**Pull request merged**
