### PR TITLE
Adjust Titles and Labels

### LINKED ISSUE #801: Adjust Lables and Titles
### What should we do?

* adjust context pad `title` attributes
* adjust palette `title` attributes
* adjust replace menu labels
* adjust button labels

### Why should we do it?

According to https://docs.google.com/document/d/1zuXLaRhNXdLa3Q4CV9J39-H5b22jDDwXotzfQV1ZsJw/edit#heading=h.bcw00wds71dr

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #801

### CODE REVIEW

**Comment by barmac** [comment]
For this one, we want to follow bpmn-js pattern, don't we?

**Comment by philippfromme** [comment]
> For this one, we want to follow bpmn-js pattern, don't we?

What do you mean?

**Review by barmac — APPROVED** [review]

**Comment by nikku** [comment]
Let's consider to mark this as a feature + breaking change as a follow-up, cf. https://github.com/bpmn-io/bpmn-js/pull/2031#pullrequestreview-1754951173.

**Comment by barmac** [comment]
I rewrote the commit: https://github.com/bpmn-io/dmn-js/commit/1fdb09ae65ec8d24608ee46e1bf3d22d4c37c008

**Pull request merged**
