### PR TITLE
297 selection update

### LINKED ISSUE #297: Inserting line break causes caret to jump to beginning

### PR DESCRIPTION
**Pull request by nikku**
This should pretty much address #297.

Closes #297

### CODE REVIEW

**Comment by philippfromme** [comment]
Output of `innerText` in Internet Explorer:

**Comment by nikku** [comment]
Expected output, right?

**Comment by nikku** [comment]
Taking into account the [IE 11 workaround](https://github.com/bpmn-io/dmn-js/pull/309/commits/8ea0638321c55b041ff6297b985f130dfa266baf) and the updates in [IE 11 selection handling](https://github.com/bpmn-io/dmn-js/pull/309/commits/f9c9b45e8d42d928e146a591ef09a0594f494d9b) this is pretty much as good as we get.

**Comment by nikku** [comment]
Merged.

**Pull request merged**
