### PR TITLE
Commit on change event and let browser handle undo of text inputs

### LINKED ISSUE #859: Make inputs commit on blur, and let browser handle undo/redo
Make inputs commit on blur, and have a separate command stack (browser native) instead of diagram-js command stack.

_Originally posted by @barmac in https://github.com/bpmn-io/dmn-js/issues/852#issuecomment-2084683824_
            

### Describe the Bug

Right now the inputs commit to the command stack which results in:

1. Slow input undo/redo
2. You can undo changes outside of the input from that input

### Steps to Reproduce

1. Type in literal expression
2. Cmd/Ctrl + Z

If you report a modeling related issue, ensure you can reproduce it on [demo.bpmn.io](https://demo.bpmn.io/dmn/new)

When reporting a library error, try to build an example that reproduces your problem. You can use our playgrounds for [viewer](https://jsfiddle.net/x2doq4vn/) or [modeler](https://jsfiddle.net/nrko5hyt/) as a starting point or put a demo up on [GitHub](https://github.com/) for inspection.

### Expected Behavior

Browser and code editor library handle inputs while command stack handles all the rest. Single undo outside of the input undoes the entire input change.

### Environment

Please complete the following information:

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by barmac**
Closes #859

### CODE REVIEW

**Comment by barmac** [comment]
@philippfromme Do you need any support with reviewing this?

**Comment by philippfromme** [comment]
@barmac Just so I understand correctly: We're trying to make inputs behave like direct-editing, where a command is issued only once I close/blur the editor?

brave_iB0l6evExR

This is not the case for other inputs yet and we're okay with that?

brave_4CXDVueQZC

**Comment by barmac** [comment]
Yes, that's the point of the PR. Right now I want to fix it in the boxed expression where I experienced the most annoying issues.

**Review by philippfromme — APPROVED** [review]
✅

**Pull request merged**
