### PR TITLE
fix(styles): fix logo position

### LINKED ISSUE #592: bpmn-io logo overlay scrollbars
__Describe the Bug__

bpmn-io layer overlays scrollbars on many browser environments.

(This of course depends on resolution, ratio and browser)
image

__Steps to Reproduce__

1. Have dmn table large enough to show scrollbars
2. See logo overlapping

__Expected Behavior__

* The margin should (maybe) be increased to not overlap the scrollbars in most scenarios
* The scrollbars should overlay the logo (and not vice versa)

__Environment__

`dmn-js v9.3.1`

__Context__
Discovered during regression testing of https://github.com/bpmn-io/dmn-js/issues/589
Introduced with https://github.com/bpmn-io/dmn-js/issues/573

### PR DESCRIPTION
**Pull request by daniloff200**
__Which issue does this PR address?__

Closes #592 

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [x] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [x] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by daniloff200** [comment]
@barmac  @nikku  can this one also be reviewed?

**Comment by barmac** [comment]
It looks good on Edge 42: 
image

@nikku What do you think?

**Review by barmac — APPROVED** [review]
I've changed the base branch to `master` as that's how we handle fixes. In the commit body _Closes #592_ is missing. When this is fixed, we can merge this PR.

Thanks for your contribution!

**Comment by daniloff200** [comment]
@barmac  thanks for your help with that. Done :)

**Comment by nikku** [comment]
Works on Linux, too:

image

**Comment by nikku** [comment]
Thanks for your contribution.

**Pull request merged**
