### PR TITLE
Align literal expression to new design

### LINKED ISSUE #515: Align literal expression editor to new design
__What should we do?__

We should adopt the latest design changes from the decision table editor / view to literal expressions

* [ ] Remove Id editing component, cf. https://github.com/bpmn-io/dmn-js/issues/496
* [ ] Placement of `View DRD` button and watermark, cf. https://github.com/bpmn-io/dmn-js/pull/511 (discussion)
* ...

__Why should we do it?__

Both modules have to be aligned.

### PR DESCRIPTION
**Pull request by barmac**
__Which issue does this PR address?__

Closes #515

__Definition of Done__

* [x] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [x] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [x] passes Continuous Integration checks
* [x] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [x] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Bildschirmfoto 2020-07-08 um 16 14 14

Is it only me ore are there are weird grey backgrounds under the content editable boxes?

**Comment by barmac** [comment]
> Bildschirmfoto 2020-07-08 um 16 14 14
> 
> Is it only me ore are there weird grey backgrounds under the content editable boxes?

What browser did you use?

**Comment by barmac** [comment]
Anyway, let's try this out with `oveflow-x: auto`.

**Comment by pinussilvestrus** [comment]
I see a problem when the content overflows the editor's box

Kapture 2020-07-09 at 8 12 40

Should we simply do the same here as with the name header? So start scrolling when it reaches the end.

**Comment by barmac** [comment]
Yeah, I think it's right approach.

**Comment by barmac** [comment]
It should work correctly now.

**Comment by oguzeroglu** [comment]
I'm testing this rn.

**Comment by philippfromme** [comment]
Pressing tab in the "code editor" tabs out of it. 💩

**Comment by barmac** [comment]
> Pressing tab in the "code editor" tabs out of it. 💩

I think in the future we could use a web code editor instead of slightly tweaked contenteditable.

**Comment by philippfromme** [comment]
Gimme a second. I'm almost done reviewing this.

**Comment by philippfromme** [comment]
Is the name not supposed to work the same as in the decision table?

image

**Comment by barmac** [comment]
> Is the name not supposed to work the same as in the decision table?
> 
> image

I guess it should. Just a sec.

**Comment by barmac** [comment]
OK Done.

**Comment by philippfromme** [comment]
Decision table text styling:

image

Literal expression text styling:

image

Needs adjustments:

```css
font-size: 21px;
font-weight: normal;
```

**Comment by barmac** [comment]
It should be complete now...

**Pull request merged**
