### PR TITLE
fix: make add column buttons focussable

### LINKED ISSUE #847: Cannot focus "add column" button
### Describe the Bug

The "add column" button (+) is inaccessible with the keyboard as it's a span without tabindex.

### Steps to Reproduce

Try to focus it.

### Expected Behavior

It should be a button with accessible label.

### Environment

Please complete the following information:

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: [e.g. 2.0.0]

---

Child of https://github.com/bpmn-io/internal-docs/issues/909

### PR DESCRIPTION
**Pull request by barmac**
Closes #847

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
While it is technically focusable now I'd consider to fine-tune the styling a little bit:

capture bGVPMP_optimized

One way to do it to add an `outline-offset: 4px;`, resulting in this:

capture GTD6YX_optimized

**Comment by barmac** [comment]
Indeed, the outline looks invisible on your screencast. In my browser (Chrome on Mac), it is easily distinguishable.

**Comment by barmac** [comment]
I've added the change from your suggestion.

**Comment by barmac** [comment]
Thanks for checking.

image

**Review by nikku — APPROVED** [review]
Works great :cake:

**Pull request merged**
