### PR TITLE
Implement new hit policy design

### LINKED ISSUE #373: Layout breaks when having very long decision names
* text doesn't wrap
* text covers _View DRD_ button

__Hint:__ This is cause by `white-space: pre;`.

fail

### LINKED ISSUE #497: Implement new hit policy design
__What should we do?__

Implement new design of the hit policy

image

Things we can consider:
* Do we have to show the explanation hint at all (or not all the time)?
* Keep the original hit policy place as an intermediate step? To avoid confusion.

__Why should we do it?__

It helps the (getting started) user to understand the hit policy options more.

Child of #494

### PR DESCRIPTION
**Pull request by barmac**
Decision name is now a part of the table as a new header with hit policy moved to the header. Aggregations and hit policies are combined in one common select.

Closes #497
Closes #373

Viewer:

viewer

Modeler:

interaction

Screenshot 2020-05-11 at 15 19 08

### CODE REVIEW

**Comment by barmac** [comment]
Reviewers: It should be a draft, sorry for missclick.

**Comment by barmac** [comment]
Concern: You don't really know what the select is about as long as you don't wait for the tooltip to appear. This might be troublesome for the users.

**Comment by barmac** [comment]
Label before the dropdown:

image

Explanation:

image

Explanation on hover:

Kapture 2020-05-12 at 8 41 13

**Comment by philippfromme** [comment]
Without any explanation when not hovering we're not really improving anything, are we? We're just moving things around.

**Comment by pinussilvestrus** [comment]
Btw. the explanation part was one of the key things which were positive in the user tests. The new position is just to make sure we have enough space for some way of explanation.

**Comment by nikku** [comment]
If it is all about the explanation not being there it can be added to the existing control (or mouse over text):

image

Hit policy is a core concept and users must be able to learn it. If you do not know it, you cannot understand the semantics of the decision table. On the other hand, it takes roughly 10 minutes to understand it (as a concept). As a result, whatever UI controls we provide are mere reminders, likely not relevant to anyone beyond the one seeing a DMN diagram for the first time.

**Comment by barmac** [comment]
Another candidate to work upon:

image

**Comment by barmac** [comment]
Current: 
image

I changed the font color from the prototype as it didn't provide enough contrast (current is confirmed to be OK on white background via https://webaim.org/resources/contrastchecker/).

**Comment by barmac** [comment]
I changed the "View DRD" button margin a bit.

**Comment by philippfromme** [comment]
> The new position is just to make sure we have enough space for some way of explanation.

Is this reason enough to move away from the standard?

**Comment by philippfromme** [comment]
A downside of this approach is that the concept of table cells breaks. The header is a large cell with additional UI inside whereas before name and hit policy where distinct cells.

See the blue selection outline:

image

**Comment by philippfromme** [comment]
Maybe it would make sense to also add the symbols of each hit policy as they are mentioned in the spec and other documentation.

image

**Comment by barmac** [comment]
Let's not merge it yet. I found a regression (enter on decision table name is creating a new rule).

**Comment by barmac** [comment]
It's strange, because the test is working properly, but then the bug occurs in the built distribution of Camunda Modeler.

**Comment by philippfromme** [comment]
Oops.

**Comment by barmac** [comment]
Oh, actually it was a problem with linking on my machine. False alarm 😅

**Pull request merged**
