### PR TITLE
chore(build): add CSS linting script via stylelint tool

### LINKED ISSUE #563: CSS linting
__Is your feature request related to a problem? Please describe.__

We should consider adding CSS linting in our build pipeline. That'd help us avoid possible mistakes such as the one we did in [v9.1.0](https://www.npmjs.com/package/dmn-js/v/9.1.0).

__Describe the solution you'd like__

Add CSS linting as an npm script.

__Describe alternatives you've considered__

None.

### PR DESCRIPTION
**Pull request by daniloff200**
__Which issue does this PR address?__

Closes #563 

Run `npm run lint-styles` , and, you will see the lint result

Selection_089

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
If we add such a script, we should add this as well to the test command / CI and make sure we got things fixed reported by the linter.

**Review by oguzeroglu — CHANGES_REQUESTED** [review]
Hey, thanks for your contribution!

After having a quick look we need to fix these two issues:

1. The CSS selection pattern should be improved. `**/*.css` selects CSS files under dist/ folder. We don't want that. Our CSS files are located under assets folder of each module.
2. As @pinussilvestrus mentioned, we need to integrate this into the existing test script. Instead of using npx we should pipe this into the test script:
    `"test": "stylelint \"VALID_CSS_FILE_PATH_PATTERN\" && lerna run test"`

**Comment by daniloff200** [comment]
hi  @oguzeroglu  and @pinussilvestrus !
Thanks for your feedback!

Thanks for pointing out, how to better set up the script, gonna do it right now

But, the comment about 
`**/*.css selects CSS files under dist/ folder.` is not completely clear for me. As I see, stylelint selects css files in each `packages/assets `folders
Maybe, this screenshot will be more informative
Selection_091

**Comment by oguzeroglu** [comment]
The `dist` folder is generated under packages/dmn-hs when you build the library with `npm run build-distro,` since it also has CSS files in it, the existing file path pattern includes these CSS files under that directory too.

**Comment by daniloff200** [comment]
Ah, got your point @oguzeroglu 
Fixed, I've added dist paths to ignored property of config

**Comment by daniloff200** [comment]
Also, if this PR will be merged, I would like to pick a task of fixing all stlylelint issues, if it's possible, of course 
That will be a suitable task for me, and, I think, can be a good 2nd contribution to the bpmn repo's

**Comment by philippfromme** [comment]
@nikku What is your opinion on adding CSS linting to this project and others?

**Comment by nikku** [comment]
> @nikku What is your opinion on adding CSS linting to this project and others?

What is the benefit? Is it comparable to eslint? Can we use stylelint universally across our tools, i.e. in the Camunda Modeler, too?

**Comment by nikku** [comment]
If it looks like the benefits (we get a little bit more unified CSS across our tools) outweights the cost (time to lint, forever) I'd give it a try. We can always remove such tool again, if we see that it does not work for us.

**Comment by nikku** [comment]
One step forward, two steps back style, you know :see_no_evil:

**Comment by philippfromme** [comment]
@nikku The idea of adding CSS linting came up after we accidentally broke the CSS of dmn-js; something that could have been prevented by linting. Enforcing a certain style of writing CSS could be another benefit. I think before thinking about merging this PR we should think about whether we want to introduce CSS linting in general. Maybe we can discuss this in the next weekly?

**Comment by nikku** [comment]
Thanks again for your contribution @daniloff200!

We decided that we will trial the tool so technically this PR is ready to be merged. In preparation I did a few changes on your feature branch.

What is obviously failing right now is a number of BEM related CSS selector lint errors. These would need to be fixed before we can merge this. You mentioned [you would tackle that](https://github.com/bpmn-io/dmn-js/pull/580#issuecomment-704556631)? If so, please go ahead and we get improved CSS files into this project :tada:.

**Comment by daniloff200** [comment]
@nikku  sure thing, gonna start  work on it today :)

**Comment by daniloff200** [comment]
@nikku  done :)

**Comment by nikku** [comment]
Thanks again for your work on this one :clap:.

Unfortunately what I found is that adding style lint to our project causes some weird issues with `eslint`. `eslint` won't properly load our configuration anymore, resulting in linting errors in places that are not actual errors (according to our code style): https://travis-ci.com/github/bpmn-io/dmn-js/builds/190531122#L268. I was not able to get to the bottom of this and need to put this PR on hold and hope for `stylelint` / `eslint` to resolve their conflict.

Steps to reproduce the issue:

```sh
git clone git@github.com:bpmn-io/dmn-js.git
cd dmn-js
npm install
npm run all
# success
npm install stylelint
npm run all
# blows up
```


For what it's worth I've already added the `hacktoberfest-accepted` label. We will eventually merge your PR, if we found the reason for this issue.

**Comment by daniloff200** [comment]
@nikku  well, that looks really weird
Perhaps, it's useful to go through issues on stylelint / eslint repos, maybe, somebody already has some solution for these cases.
Also, if not, it can be a good idea to create an issue there, and ask  projects maintainers about that

Thanks for adding a label, hope, in the future that changes will be useful :)

**Comment by nikku** [comment]
Well, as a last resort I've re-setup stylelint (and re-created the package lock modification). It works now, so apparently the way you installed the library broke something? Anyhow. We are good now. :+1: 

Hacktoberfest badge well deserved :1st_place_medal:

**Comment by daniloff200** [comment]
Yay !
Actually,  idk, what can be wrong in that case, potentially some package-lock issues during the merge maybe :sweat_smile:  But, I've never seen cases before, that there's no any errors related to package-lock, but, linter works not correct.
Anyway, glad, that we've finally able to finish this task and merge it!

Thanks for your help & support, @nikku :)

**Pull request merged**
