### PR TITLE
Remove unnecessary click event cancel action

### LINKED ISSUE #546: Hit Policy Not Closed on Cell Click
__Describe the Bug__

__Steps to Reproduce__

1. Click Hit Policy to open dropdown
2. Click a cell

__Expected Behavior__

Dropdown should close on click outside of dropdown.

__Environment__

 - Library version: 9

### PR DESCRIPTION
**Pull request by barmac**
Closes #546

__Definition of Done__

* [x] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [x] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [x] passes Continuous Integration checks
* [x] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [x] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by philippfromme** [comment]
Doesn't this make https://github.com/bpmn-io/dmn-js/pull/561#pullrequestreview-461575794 obsolete?

**Comment by MaxTru** [comment]
> Doesn't this make [#561 (review)](https://github.com/bpmn-io/dmn-js/pull/561#pullrequestreview-461575794) obsolete?

Or the other way around since #561 is more global?

**Comment by philippfromme** [comment]
> Or the other way around since #561 is more global?

As soon as we decide to start cancelling `mousedown` events we end up with the same issue again. It's just not a good idea to cancel events if not necessary. You never know who might be interested in them. This is why I'd prefer this fix instead of #561.

**Comment by barmac** [comment]
I'd opt for merging both this and https://github.com/bpmn-io/dmn-js/pull/561. Although with #561 merged this PR does not change anything regarding Hit Policy dropdown, it still removes unwanted behavior of cancelling click events without good reason. I will rename commit and PR title so that it reflects correctly the content.

**Comment by philippfromme** [comment]
> I'd opt for merging both this and #561. Although with #561 merged this PR does not change anything regarding Hit Policy dropdown, it still removes unwanted behavior of cancelling click events without good reason. I will rename commit and PR title so that it reflects correctly the content.

But why would we need #561 if this PR fixes the actual issue? I don't get it?

**Comment by barmac** [comment]
> > I'd opt for merging both this and #561. Although with #561 merged this PR does not change anything regarding Hit Policy dropdown, it still removes unwanted behavior of cancelling click events without good reason. I will rename commit and PR title so that it reflects correctly the content.
> 
> But why would we need #561 if this PR fixes the actual issue? I don't get it?

#561 implements behavior described in https://github.com/bpmn-io/dmn-js/issues/546#issuecomment-667086995:

> I'd expect the dropdown to close whenever there is mouse interaction outside of it.

I understand it as "We close dropdown as soon as there's any mouse interaction outsided of it" which translates to close on mousedown instead of closing on click. We don't need to wait until user lifts mouse button to get that interaction was started outside of dropdown. See also the list in https://github.com/bpmn-io/dmn-js/issues/546#issuecomment-667047961. I'd rather not wait until there are new issues about "dropdown doesn't close on new rule", "dropdown doesn't close on new column" etc.

**Pull request merged**
