### PR TITLE
feat(drd): accept default colors for DRD elements

### LINKED ISSUE #679: Accept default fill and stroke colors for DRD elements
Hey modeling team!

__Is your feature request related to a problem? Please describe.__

I'm currently implementing DMN in a project including a DRD Panel. Since we have a dark mode in the project we'd like to customize the fill and stroke colors of DRD elements.

__Describe the solution you'd like__

It would be nice to be able to provide a defaultStrokeColor and defaultFillColor similar to the [implementation in bpmn-js](https://github.com/bpmn-io/bpmn-js/commit/dc1f18a4972cee2d9e1bf46a6412dbb93b28506a). Is something like this planned in the near future?

__Describe alternatives you've considered__

I tried to style the svg elements from outside. It works, but it does not feel as nice as passing default colors. Happy for any more input!

```css
.dmn-drd-container .djs-visual rect {
  stroke: #ffffff !important;
  fill: #313238 !important;
}

.dmn-drd-container .djs-label {
  fill: #ffffff !important;
}

.dmn-drd-container .djs-connection polyline {
  stroke: #ffffff !important;
}
```

__Additional context__

These are the design requirements for DRD dark mode:
image
(Source: https://app.zeplin.io/project/5ae9bee76332bd9e298b5d41/screen/61fd48a87a576f9b9ff25dab)

### PR DESCRIPTION
**Pull request by barmac**
Closes #679

### CODE REVIEW

**Review by MaxTru — COMMENTED** [review]
works!

Minor, but to consider: what about adding basic JSDocs just for this new feature so that it is easier discovered I can pass an object options like 
```
{
  defaultFillColor: ...,
  defaultStrokeColor: ...
}
```

I know there is no / rare JSDoc now as well...

Screenshot_20220318_100700

**Comment by barmac** [comment]
Sure, good idea.

**Comment by barmac** [comment]
@MaxTru I added the documentation via https://github.com/bpmn-io/dmn-js/pull/693/commits/c750aebda1a280b90bb6800266cba22adb1e1810

**Comment by MaxTru** [comment]
I like with the JSDocs.

**Review by MaxTru — APPROVED** [review]

**Pull request merged**
