### PR TITLE
Correctly update examples

### PR DESCRIPTION
**Pull request by barmac**
This allows to keep `package-lock.json` files updated accordingly.

Related to https://github.com/bpmn-io/dmn-js-examples/issues/18

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by nikku** [comment]
What was wrong about the old way of updating?

From what I understand this PR now force installs dmn-js, if it is used or not, does not matter.

**Comment by nikku** [comment]
To fix bpmn-io/dmn-js-examples#18 we could update the package-lock after each "patch", too.

**Comment by nikku** [comment]
Obviously one could argue that every project in dmn-js-examples should depend on dmn-js. In this case the PR is :rocket:.

**Comment by barmac** [comment]
> What was wrong about the old way of updating?

It was impossible to run `npm ci `.

> Obviously one could argue that every project in dmn-js-examples should depend on dmn-js. In this case the PR is 🚀.

Yeah, that's what I'd expect.

**Comment by nikku** [comment]
All right then.

**Comment by nikku** [comment]
Alternative, as mentioned would have been to rebuild the package lock, which is a reasonable behavior after updating the examples, too.

**Pull request merged**
