### PR TITLE
chore: upgrade inferno to 5.6.3

### PR DESCRIPTION
**Pull request by jessevanmuijden**
### Proposed Changes

Upgrade inferno to version 5.6.3. which includes a backport of a fix for handling events in the shadow dom.

Closes https://github.com/bpmn-io/dmn-js/issues/631, the first item at least ("View DRD" and "+" buttons don't work (nothing happens on click)) 

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
Hi, can you please add a test case so that we can confirm the issue is solved?

**Comment by nikku** [comment]
@barmac I'd be fine to [rely on the upstream test coverage](https://github.com/infernojs/inferno/pull/1669/files#diff-0e0a820a8d4039de4fb33077b3ed84c2549077af5c96c833a26486ac068f6e06). Of course an additional test here would ensure that we don't accidentally break this, if we ever switched to another VDOM utility.

**Comment by barmac** [comment]
I'd say let's merge this, and if the issue persists we can reconsider.

**Comment by barmac** [comment]
Released as v16.6.1

**Pull request merged**
