### PR TITLE
Implement variable suggestions

### LINKED ISSUE #785: Implement variable suggestions
* [x] I want to browse my available variables.
* [x] I want to autocomplete a variable to speed up development, and to ensure I spell it correctly.

### PR DESCRIPTION
**Pull request by barmac**
https://github.com/bpmn-io/dmn-js/assets/28307541/aa4ec739-b576-4957-b54c-30d77d2265fa

* [x] variable suggestions are available in input expression
* [x] variable suggestions are available in table cell
* [x] variable suggestions are available in literal expression

Closes #785

### CODE REVIEW

**Comment by marstamm** [comment]
Works great, love the feature! Have you considered adding an integration test for the feature?

**Comment by marstamm** [comment]
I was thinking that we could check that variables are passed to the Editor component, if that is manageable. If not, feel free to merge anyway

**Comment by barmac** [comment]
@marstamm Check out https://github.com/bpmn-io/dmn-js/pull/791/commits/1b2efbf973b1c13c44800dbd0de43b833688610a

**Review by marstamm — APPROVED** [review]

**Comment by nikku** [comment]
Amazing stuff! :tada:

**Comment by nikku** [comment]
Let's ship it :boat:

**Pull request merged**
