### PR TITLE
fix(drd/drd-rules): allow association regardless of connection direction

### PR DESCRIPTION
**Pull request by philippfromme**
Related to https://github.com/camunda/camunda-modeler/issues/1817
Related to https://github.com/camunda/camunda-modeler/issues/1702
Related to https://github.com/camunda/camunda-modeler/issues/1763

### CODE REVIEW

**Comment by nikku** [comment]
:clap:

**Comment by barmac** [comment]
@philippfromme will you cherry-pick this to master? We could release a patch before the decision table head stuff is finished.

**Comment by philippfromme** [comment]
Shit. It was meant to go to `master`. 🙅

**Comment by philippfromme** [comment]
I'll fix it.

**Comment by philippfromme** [comment]
Done. Fix is now on `master`, `master` merged into `develop`.

**Comment by barmac** [comment]
👏

**Pull request merged**
