### PR TITLE
Fix Literal Expression Styles

### LINKED ISSUE #607: Literal Expression Styles Broken
__Describe the Bug__

Literal expression overflow isn't being handled.

image

Example: https://codesandbox.io/s/literal-expression-style-issue-6roo6

Related to https://github.com/camunda/camunda-modeler/issues/2019

__Steps to Reproduce__

1. Open literal expression
2. Reduce height of its container until it overflows

__Expected Behavior__

Overflow is handled.

__Environment__

 - Library version: >9

### PR DESCRIPTION
**Pull request by philippfromme**
__Which issue does this PR address?__

Closes #607
Related to camunda/camunda-modeler#2019

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by barmac** [comment]
This looks good, but unfortunately I cannot select text area when I click on empty space anymore.
dmn

Also, it would be cool if the text area could grow with text inside until we hit the bottom of the container. Still, this is an additional feature request.

**Comment by philippfromme** [comment]
> This looks good, but unfortunately I cannot select text area when I click on empty space anymore.

I cannot reproduce this on my machine.

bar

**Comment by philippfromme** [comment]
> Also, it would be cool if the text area could grow with text inside until we hit the bottom of the container. Still, this is an additional feature request.

The scope of this issue is to fix the overflow. I agree that an even better solution would be a sticky header and scrolling content but I would rather create a separate issue for that.

**Comment by barmac** [comment]
OK, it was a problem with my config.

**Pull request merged**
