### PR TITLE
Remove wrong reference to woff2 font

### LINKED ISSUE #197: Wrong reference to woff2 font
The [dmn.css](https://github.com/bpmn-io/dmn-js/blob/b59858a4e5a8f4a286afb26e5ab32dc122ea3120/assets/dmn-font/css/dmn.css#L5) file references to a not existing `dmn.woff2` file.

### PR DESCRIPTION
**Pull request by akkie**
I'm not sure if the font is missing or if the reference to the font is wrong. So in the case the reference is wrong then this fixes #197. Otherwise please feel free to close the issue.

### CODE REVIEW

**Comment by ricardomatias** [comment]
I've added back the missing `.woff2`. Thanks for your feedback.

**Comment by akkie** [comment]
@ricardomatias You have added a [config.json](https://github.com/bpmn-io/dmn-js/blob/ffadb252bff01fedc307392ff626e56ca7867af3/assets/dmn-font/config.json), but no `.woff2` font. Do I miss something?

**Comment by ricardomatias** [comment]
Commit issue, it's fixed now.

**Comment by akkie** [comment]
:+1: Thanks!

**Pull request closed without merging**
