### PR TITLE
fix: solve audit errors

### PR DESCRIPTION
**Pull request by pinussilvestrus**
* executed `npm audit fix`

__Which issue does this PR address?__

Related to #609

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Executing `npm audit fix` seems to not do the trick, since there are still issues open, also the ones mentioned in https://github.com/bpmn-io/dmn-js/issues/609 (as far I can overview it).

Proposal: 
* Let's discuss a basic strategy regarding those security vulnerabilities issues coming from other libraries
* Investigate which security issues we want to fix

**Comment by pinussilvestrus** [comment]
I verified the two issues described in #609 with the sync CLI

```sh
Issues with no direct upgrade or patch:
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-MINIMIST-559764] in minimist@1.2.0
    introduced by dmn-js@9.4.0 > dmn-js-shared@9.4.0 > inferno@5.0.6 > opencollective@1.0.3 > minimist@1.2.0 and 5 other path(s)
  This issue was fixed in versions: 0.2.1, 1.2.3
  ✗ Denial of Service [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311] in node-fetch@1.6.3
    introduced by dmn-js@9.4.0 > dmn-js-shared@9.4.0 > inferno@5.0.6 > opencollective@1.0.3 > node-fetch@1.6.3 and 5 other path(s)
  This issue was fixed in versions: 2.6.1, 3.0.0-beta.9
```

Seems like these are coming from inferno, which we can't update currently.

**Comment by nikku** [comment]
That `opencollective` thing is an actual run-time dependency, via `inferno`: https://github.com/infernojs/inferno/blob/v5.0.6/packages/inferno/package.json#L54.

To fix it, we'd need to patch inferno to not use the broken (and outdated) library.

**Comment by pinussilvestrus** [comment]
Let's close this one to keep our board clean and do proper housekeeping later on (e.g. by also cleaning up the sub-packages).

**Pull request closed without merging**
