### PR TITLE
Integrate diagram-js@15.1.0

### PR DESCRIPTION
**Pull request by jarekdanielak**
Related to https://github.com/bpmn-io/internal-docs/issues/1081

### Proposed Changes

 

Update to `diagram-js@15.1.0` and `diagram-js-direct-editing@3.2.0`.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by jarekdanielak** [comment]
`table-js` updated ✅

**Comment by nikku** [comment]
Given everything what we have discussed in prior conversations, what is [this change](https://github.com/bpmn-io/dmn-js/pull/915/commits/250b8cc7b2a4466b918b616604b70af1da4b1804) for our users? It is a _major_ breaking change, as the keyboard.bindTo is no longer available.

**Comment by nikku** [comment]
Updated via https://github.com/bpmn-io/dmn-js/pull/915/commits/ef80f15705ca1f0eade92f0d14345cce3a1eb310. Will merge with some additional housekeeping.

**Comment by nikku** [comment]
Published as `dmn-js@17.0.0`.

**Pull request merged**
