### PR TITLE
Upgrade diagram-js

### PR DESCRIPTION
**Pull request by smbea**

### CODE REVIEW

**Comment by nikku** [comment]
Currently manually testing this :eyes:

**Comment by nikku** [comment]
Works for me (conducted manual, trying-to-break-it smoke test). :+1:

**Review by nikku — COMMENTED** [review]
Consider to bump in table-js -> dmn-js, too.

This way we get rid of some duplication.

**Comment by nikku** [comment]
> https://github.com/bpmn-io/dmn-js/pull/722#issuecomment-1342800528

Yes.

**Comment by barmac** [comment]
I can confirm this works fine on my machine too.

**Review by barmac — APPROVED** [review]

**Pull request merged**
