### PR TITLE
fix(decision-table): correctly display bottom border

### LINKED ISSUE #540: Table bottom dissapears sometimes
__Describe the Bug__

This bug can be observed when I add the 4th row in the GIF:

table-glitch

__Steps to Reproduce__

1. Add new rows to a DMN table
2. Do a couple of mouse-over/mouse-outs
3. If issue is not reproduced, go to step 1

__Expected Behavior__

Bottom of the table does not disappear.

__Environment__

Please complete the following information:

 - Browser: Chrome 83
 - OS: Mac OS
 - Library version: current `develop` branch

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #540

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by philippfromme** [comment]
The fix is working. However, I noticed that the color doesn't work for the double border between input and output cells.

image

Adding

```css
.dmn-decision-table-container tfoot.add-rule .output-cell {
  border-left: 3px double #AAA;
}


.dmn-decision-table-container tfoot.add-rule:hover .output-cell {
  border-left: 3px double #444;
}

.dmn-decision-table-container tfoot.add-rule:hover .output-cell + .output-cell {
  border-left: 1px solid #444;
}
```

**Comment by philippfromme** [comment]
@barmac @pinussilvestrus What are your thoughts on my comment?

**Comment by pinussilvestrus** [comment]
This is not something which comes from this PR but is present for a while now: https://demo.bpmn.io/dmn/s/check-order

I'd like to have this fix as well.

**Comment by philippfromme** [comment]
@pinussilvestrus I know but I'd like to fix this if we're touching the footer anyway.

**Comment by barmac** [comment]
Have you tried it out to just set `border-left/right-color`?

**Comment by philippfromme** [comment]
> Have you tried it out to just set `border-left/right-color`?

Didn't work for me.

**Comment by barmac** [comment]
@philippfromme Try now.

**Comment by pinussilvestrus** [comment]
Progress, I like 🚀

**Pull request merged**
