### PR TITLE
chore: update to inferno@5.6.1

### PR DESCRIPTION
**Pull request by pinussilvestrus**
__Which issue does this PR address?__

Related to #609 

__Acceptance Criteria__

* [ ] Corresponds to the concept 
* [ ] Corresponds to the design 

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
We have some crashing tests on Firefox

image

This _could_ be caused due to changes they did with contenteditables (cf. https://github.com/infernojs/inferno/commit/32ac467ce054c5c43ab5e725c8450183b7d7911c). I'll investigate whether and how we could deal with it.

**Comment by pinussilvestrus** [comment]
I tested a bit through different browsers and it seems like we can freely upgrade to `inferno@5.6.1` without having quirks.

I would proceed with
* merging this
* asking the guys from inferno to release the patch version
* integrating it
* create an alpha release with the patched inferno version and consult other teams to test it out (as @nikku suggested)

**Comment by nikku** [comment]
Great!

**Review by barmac — APPROVED** [review]
I couldn't find any problems either on Chrome or Safari. All tests were green.

**Pull request merged**
