### PR TITLE
Embed FEEL editor in table cell

### LINKED ISSUE #774: Embed FEEL editor in Table cells
* [x] Table cell is a FEEL editor
* [x] Table cell is a plain input if expression language is different than FEEL
* [ ] `Escape` blurs the input
* [x] I can select suggestion with `Enter`
* [x] I can select suggestion with mouse click
* [ ] Performance is acceptable even in a big table
  * [x] FEEL editor is embedded only for active cell
* [x] Focussed cell changes when use navigates cells with keyboard (tab, enter)

### PR DESCRIPTION
**Pull request by barmac**
Closes #774

### CODE REVIEW

**Review by nikku — APPROVED** [review]
Great stuff! 

There is only a minor thing I found, which is that the code editor seems to be one pixel larger than the cell, causing a little bit of movement on focus.

capture I6EKoW_optimized

**Comment by barmac** [comment]
I cannot reproduce this o.O

**Comment by barmac** [comment]
Safari looks OK

**Comment by barmac** [comment]
It appears `line-height: normal` is different for Arial and monospace font in Firefox.
I could change all fonts in decision table to monospace, or force `line-height: 1` (or other exact value).

With monospace:

https://github.com/bpmn-io/dmn-js/assets/28307541/656d18f9-a6eb-4e0a-86b5-c906858ceca8

**Comment by nikku** [comment]
I would honestly not mind making the elements in the table all monospace. Let's ship this (and await feedback).

**Comment by nikku** [comment]
Let's feature the font change in the CHANGELOG as well.

**Comment by barmac** [comment]
> Let's feature the font change in the CHANGELOG as well.

Done via https://github.com/bpmn-io/dmn-js/commit/3edc685085ed1cfeb0c9e4a98091f9d5127e7726
Thanks for pointing this out.

**Pull request merged**
