### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by nikku**
### Proposed Changes

Bump various dependencies, ensure the house is prepared for autumn season.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Review by jarekdanielak — APPROVED** [review]

**Review by barmac — APPROVED** [review]
Now the dev setup is working again. Thanks!

**Comment by barmac** [comment]
I'm gonna have a look why this test is failing:
>  Chrome Headless 129.0.0.0 (Linux x86_64) simple mode should render at top right corner FAILED
  	AssertionError: expected false to be true
  	    at Context.eval (webpack-internal:///./test/spec/features/simple-mode/SimpleModeSpec.js:93:64)

**Comment by barmac** [comment]
So the test is consistently failing on CI on one of the assertions:

```javascript
    expect(simpleModeButton.classList.contains('right')).to.be.true;
    expect(simpleModeButton.classList.contains('bottom')).to.be.true;
```

This is related to DOM measurements which may sometimes fail on CI.

**Comment by nikku** [comment]
Dropped puppeteer bump, now all things are green.

**Pull request merged**
